apiVersion: batch/v1
kind: Job
metadata:
  name: first-job
spec:
  template:
    metadata:
      name: first-job-pod
    spec:
      containers:
      - name: first-job-container
        image: busybox
        command:
          - "bin/sh"
          - "-c"
          - "for i in {1..5}; do echo wow $i = $((1 + RANDOM % 70)); done"
      restartPolicy: Never