apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis

    volumeMounts:
      - name: my-hostpath-storage  # Corrected indentation
        mountPath: "/persisted"   # Fixed placement under volumeMounts

  # Define volume
  volumes:
  - name: my-hostpath-storage
    hostPath:
      path: "/var/lib/host-store"
