apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    
    - name: apache-container
      image: httpd
      resources:
        requests:
          cpu: "500m"   # 500 millicores (0.5 vCPU)
          memory: "256Mi"  # 256 MiB of memory
        limits:
          cpu: "1000m"  # 1 vCPU
          memory: "512Mi"  # 512 MiB of memory

    - name: redis-container
      image: redis
      resources:
        requests:
          cpu: "400m"   # 500 millicores (0.5 vCPU)
          memory: "64Mi"  # 256 MiB of memory
        limits:
          cpu: "500m"  # 1 vCPU
          memory: "128Mi"  # 512 MiB of memory