apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  namespace: default
data:
  # Connection database config
  database: mongodb
  database_url: mongodb://localhost:27017




---
# another yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-env

spec:
  restartPolicy: Never
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - configMapRef:
        name: my-cm
    command: ["/bin/sh", "-c", "echo 'ConfigMap Variables:'; echo 'database: ' $database; echo 'database_url: ' $database_url"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    

